### ISSUE TITLE
Profile page crashes app if user has no votes

### ISSUE THREAD

**Issue by benstr** [meteoric/meteorhunt#1]
The ProfileController data:votedProducts is causing the app to crash if the user has no votes.

**console**

```
Exception from Tracker recompute function: Error: $in needs an array
```

**route controller in question**

```
ProfileController = AppController.extend({
  waitOn: function () {
    if (Meteor.user()) {
      return Meteor.subscribe('votedProducts', Meteor.user());
    }
  },
  data: function () {
    if (Meteor.user()) {
      return {
        user: Meteor.user(),
        votedProducts: Products.find({_id: {$in: Meteor.user().profile.votedProductIds}})
      }
    }
  }
});
```

**Comment by benstr** [comment]
Fixed in PR #2

**Comment by rgoomar** [comment]
I think this could easily be fixed with a simple initialization of the `Meteor.user().profile.votedProductIds` as an empty array if no data exists.

What I think is happening right now is that if none of them exist, the value of that is `undefined` which can cause the above error to occur since `$in` is looking for an array.

**Comment by rgoomar** [comment]
My guess is that it could be fixed by changing this:

```
Products.before.insert(function (userId, doc) {
  doc.createdAt = new Date();
});
```

to

```
Products.before.insert(function (userId, doc) {
  doc.createdAt = new Date();
  doc.profile.votedProductIds = [];
});
```

**Comment by benstr** [comment]
That will work too. nice!
